# **Задание для повторения материала

In [2]:
import numpy as np

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел от 12 до 24 невключительно

In [8]:
a = np.linspace(12, 24, 12, endpoint=False)
a

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [30]:
a_2_6 = a.reshape(2, 6)
print(a_2_6, end='\n\n')

a_6_2 = a.reshape(6, 2)
print(a_6_2, end='\n\n')

a_3_4 = a.reshape(3, 4)
print(a_3_4, end='\n\n')

a_4_3 = a.reshape(4, 3)
print(a_4_3, end='\n\n')

a_12_1 = a.reshape(12, 1)
print(a_12_1, end='\n\n')

[[12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]

[[12. 13.]
 [14. 15.]
 [16. 17.]
 [18. 19.]
 [20. 21.]
 [22. 23.]]

[[12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]]

[[12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]
 [21. 22. 23.]]

[[12.]
 [13.]
 [14.]
 [15.]
 [16.]
 [17.]
 [18.]
 [19.]
 [20.]
 [21.]
 [22.]
 [23.]]



3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1
 (в трех примерах — для обозначения числа столбцов, в двух — для строк).

In [37]:
a_2_6 = a.reshape(2, -1)
print(a_2_6, end='\n\n')

a_6_2 = a.reshape(-1, 2)
print(a_6_2, end='\n\n')

a_3_4 = a.reshape(3, -1)
print(a_3_4, end='\n\n')

a_4_3 = a.reshape(-1, 3)
print(a_4_3, end='\n\n')

a_12_1 = a.reshape(12, -1)
print(a_12_1, end='\n\n')

[[12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]

[[12. 13.]
 [14. 15.]
 [16. 17.]
 [18. 19.]
 [20. 21.]
 [22. 23.]]

[[12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]]

[[12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]
 [21. 22. 23.]]

[[12.]
 [13.]
 [14.]
 [15.]
 [16.]
 [17.]
 [18.]
 [19.]
 [20.]
 [21.]
 [22.]
 [23.]]



4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Если говорить об этом массиве с программной точки зрения, то все же нет.
Этот объект все-таки содержит в себе массивы, содержащие по одному элементу.

Если же говорить об этом массиве более абстрактно, то можно сказать, что это одномерная последовательность чисел

5. Создать массив из 3 строк и 4 столбцов,
состоящий из случайных чисел с плавающей запятой из нормального распределения со средним,
равным 0 и среднеквадратичным отклонением, равным 1.0.
Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [44]:
rand_arr = np.random.randn(3, 4)
print(rand_arr, end='\n\n')

print(rand_arr.flatten())

[[ 0.04470776  1.84925231  0.02262348  0.58944531]
 [-0.25938854  1.01785634 -2.6826407  -0.19944322]
 [ 0.38781151  0.07614923  1.26071694  0.65841874]]

[ 0.04470776  1.84925231  0.02262348  0.58944531 -0.25938854  1.01785634
 -2.6826407  -0.19944322  0.38781151  0.07614923  1.26071694  0.65841874]


6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [48]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел,
убывающих от 20 до 1 невключительно с интервалом 2.
В чем разница между массивами a и b?

In [50]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Разница между массивами a и b, полагаю, в размерности
Первый является одномерным массивом, содержащий 10 элементов,
второй же массив является двумерным и содержит одну строку, содержащую 10 элементов

8. Вертикально соединить массивы a и b.
a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше,
чем число строк двумерного массива b, состоящего из единиц.
Итоговый массив v должен иметь атрибут size, равный 10.

Итак, выясним же размеры матриц a и b.
Во-первых, количество столбцов в a и в b должно быть одинаковым. Назовем его $m$.

Количество строк в a - $n_a$<br>
Количество строк в b - $n_b$<br>

Имеем $(n_a + n_b) \cdot m = 10,\ где\ n_a = n_b - 1,\ n_a > 1$<br>
10 Раскладывается на простые множители только на 2 и 5
(10 и 1 не подходит из-за того, что число строк должно быть нечетным).

Соответственно $m = 2$, $n_a = 2$, $n_b = 3$

In [62]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
result = np.vstack((a, b))
print(result)
print("result.size = ", result.size)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
result.size =  10


9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.
Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [71]:
a = np.arange(12)
print(a, end='\n\n')

A = a.reshape(4, 3)
print(A, end='\n\n')

At = A.transpose()
print(At, end='\n\n')

B = A @ At
print(B, end='\n\n')
print(np.linalg.det(B))

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]

0.0


Матрица B имеет размер 4х4.<br>
Обратную матрицу для матрицы B вычислить не получится т.к. ее определитель равен нулю

10. Инициализируйте генератор случайных чисел с помощью объекта seed, равного 42.

In [81]:
np.random.seed(42)

11. Создайте одномерный массив c,
составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [82]:
c = np.random.randint(0, 16, 16)
print(c)
print(c.size)

[ 6  3 12 14 10  7 12  4  6  9  2  6 10 10  7  4]
16
