# Задача №3

Найдите скалярное произведение столбцов массива a_centered.
В результате должна получиться величина a_centered_sp.
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [62]:
import numpy as np

In [67]:
a_centered = np.load("arrays/a_centered.npy")

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [71]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp

[-1.  0.  1.  1. -1.]
[-2.4 -0.4  2.6  1.6 -1.4]


8.0

In [73]:
covariance = a_centered_sp / (a_centered.shape[0] - 1)
covariance.round(4)

2.0

In [74]:
np.save("arrays/covariance.npy", covariance)